### ISSUE TITLE
Home Assistant

### ISSUE THREAD

**Issue by phmllr** [RobinMeis/Junkers_1-2-4_ESP32#3]
Ich habe ewig nach einer Lösung gesucht meine Junkers endlich smart zu bekommen. Danke für dein Einfallsreichtum! Ich würde das Projekt gerne nachbauen und in HA integrieren( was durch mqtt kein Problem sein sollte)
Doch ich habe eine Frage:
Wie verhält sich die Therme wenn ich sie aus dem standby hole also aktiv setzte und die Raumtemperatur erreicht ist? Schaltet die Therme dann ab?
Hintergrund ist folgender: 
Ich habe eine 4 Raum Wohnung und an jedem Heizkörper ein smartes Thermostat. Nun hätte ich es gerne so, dass wenn ein heizkörperthermostat Wärme benötigt, die Therme anspringt. Doch wenn der Temperatursensor an der Platine des ESP sagt Soll und Ist Temp. Sind gleich würde die Therme ja nicht angehen oder ?
Ich hoffe ich habe es halbwegs verständlich erklärt und du kannst mir irgendwie auf die Sprünge helfen.

**Comment by RobinMeis** [comment]
Ich habe meine Therme inzwischen auch im Homeassistant. Die Firmware habe ich allerdings nicht dafür angepasst, sondern einen Adapter in Nodered gebaut. Nichts hält ja länger als ein Provisorium.

Grundsätzlich ist es so, dass die Junkers Etagenheizungen Raumgeführt sind. So macht es auch der originale Regler. Dessen Verhalten habe ich damals analysiert und nachgebaut. Der Regler hier stellt damit eigentlich nur eine WLAN Variante des Originals dar. Das von dir beschriebene Problem besteht also tatsächlich. Das ist natürlich eigentlich sehr unpraktisch, weil der Wärmebedarf pro Raum überhaupt nicht berücksichtigt wird. Bei mir hängt hängen Therme und Regler zum Beispiel in der Küche und dort heize ich nur sehr wenig. Die Therme würde also nie abschalten, sondern die Umwälzpumpe immer aktiv bleiben, selbst wenn alle Thermostate geschlossen sind.

Ich habe das bei mir über den Homeassistant automatisiert. Meine Heizungsthermostate geben den Heizbedarf als PI Heating Demand aus. Der Homeassistant setzt dann bei bestehendem Bedarf die Zieltemperatur für die Therme entsprechend hoch. Du müsstest die Zieltemperatur am Regler dann einfach so hoch einstellen, dass sie in dem Führungsraum niemals erreicht werden kann. Leider ist zur 1-2-4 Schnittstelle seitens Junkers nichts dokumentiert. Alles, was dazu bekannt ist, basiert auf eigenen Untersuchungen und vagen Annahmen. Ich kann daher nicht sagen, welche Auswirkungen das dann nicht ganz korrekte Verhalten des Reglers hat. Da das selbe Problem aber auch mit dem Originalregler besteht, mache ich mir da keine Gedanken. Bei mir entscheidet der Regler letztlich nur über An oder Aus. Ob die Flamme gezündet wird entscheidet die Therme schließlich selbst aus der Differenz zwischen Vor- und Rücklauftemperatur.

Das ist natürlich keine ideale Lösung, mehr gibt aber auch eine Integration in den Homeassistant meines Wissens nicht her. Zumindest dann nicht, wenn du die Therme als Temperaturregler einbinden möchtest.

**Comment by phmllr** [comment]
Hey danke für die schnelle Antwort!

Wenn ich dich richtig verstehe soll ich die Solltemp. auf z.B 30°C stellen damit es nie erreicht wird. Schaltet die Therme dann von allein ab wenn alle Heizkörper zu sind und Vor und Rücklauf annähernd gleich warm sind?

**Comment by RobinMeis** [comment]
Genau so kannst du es machen. Die Therme schaltet allerdings nicht von alleine ab. Die Umwälzpumpe wird weiter gegen die geschlossenen Thermostate anpumpen. Der Heizkreis wird auf Temperatur gehalten. Die Flamme wird also ausgeschaltet, bis der Heizkreis durch Verluste wieder zu weit abgekühlt ist. Dann wird die Flamme wieder zünden, unabhängig davon, ob tatsächlich Heizbedarf besteht. Bei mir hat die Pumpe eine Stromaufnahme von ca. 50 Watt. Auch die werden dann permanent verbraucht.

Daher macht es Sinn, dass du mit einer Automatisierung im Home Assistant den Heizbedarf deiner Thermostate abfragst und die Zieltemperatur des Heizungsreglers wieder auf 5°C bis 10°C zu setzen, um die Therme vollständig abzuschalten. Das hat auch den Vorteil, dass du die Thermostate einfach aufdrehen kannst und die Therme dann automatisch angeht. Sehr praktisch war das auch in den kalten Nächten der letzten zwei Wochen. Da ist die Therme dann auch nachts mal für eine halbe Stunde angesprungen, damit die Räume nicht zu weit auskühlen. Thermostate hatte ich da einfach auf 15°C stehen gelassen.

**Comment by phmllr** [comment]
Sehr gut. 
Vielen Dank ich werde testen und berichten!
